### ISSUE TITLE
Recomendations

### ISSUE THREAD

**Issue by ilyosdev** [asakew/Newz-App-UI#1]
You are not using sass in an inappropriate way. https://www.hongkiat.com/blog/sass-tips-tools-for-developers/ Read this article plz.

**Comment by asakew** [comment]
tug'risi cssga urganb qolgan ekanman, va barca kodlarni yozb bulgannmdan keyn 100% SASSga utazaman

**Comment by asakew** [comment]
lekn Ilyos etiborngz ucun raxmat :)

**Comment by ilyosdev** [comment]
arzimaydi
